# Generated by Django 3.2.15 on 2023-05-15 23:38

from django.db import migrations


class Migration(migrations.Migration):
    
    def transfer_prices(apps, schema_editor):
        OrderElement = apps.get_model('foodcartapp', 'OrderElement')
        order_items = OrderElement.objects.all()
        if order_items.exists():
            for order_item in order_items.iterator():
                order_item.price = order_item.product.price
                order_item.save()

    dependencies = [
        ('foodcartapp', '0039_orderelement_price'),
    ]

    operations = [
        migrations.RunPython(transfer_prices),
    ]
