# Generated by Django 3.2.15 on 2023-05-17 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230517_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заказ создан'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
    ]
