# Generated by Django 3.2.15 on 2023-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230517_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('C', 'Оплата наличными при получении'), ('CD', 'Оплата картой при получении'), ('O', 'Оплата картой онлайн')], max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
