# Generated by Django 3.2.15 on 2023-06-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_orderelement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Создан'), ('A', 'Принят'), ('P', 'Готовится'), ('D', 'Передан в доставку'), ('DN', 'Заказ выполнен')], db_index=True, default='C', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
